### ISSUE TITLE
🐛 [BUG] - Private notes api returning content when wrong passkey is passed or even when no passkey is passed

### ISSUE THREAD

**Issue by chirag3003** [BRAVO68WEB/shx#106]
### Description

Private notes can be fetched without a passkey

### Reproduction URL

https://github.com/bravo68web/shx

### Reproduction steps

```bash
Make an api request to get note by id for a private note but without passing a passkey
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

**Comment by BRAVO68WEB** [comment]
Fixed in #108
